"""Added new columns to user and media tables

Revision ID: 13b71ec1083c
Revises: d9a730b9868c
Create Date: 2025-11-04 17:55:36.815665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13b71ec1083c'
down_revision: Union[str, Sequence[str], None] = 'd9a730b9868c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('background_pic_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'background_pic_public_id')
    op.drop_column('users', 'profile_pic_public_id')
    op.drop_column('media', 'public_id')
    # ### end Alembic commands ###
