"""add new fields to Media

Revision ID: 512ec942ddd0
Revises: 85436b786386
Create Date: 2025-10-09 10:52:29.565892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '512ec942ddd0'
down_revision: Union[str, Sequence[str], None] = '85436b786386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mediareaction')
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('comment_media_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comment_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_pkey'))
    )
    op.create_table('mediareaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_like', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('mediareaction_media_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mediareaction_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mediareaction_pkey'))
    )
    # ### end Alembic commands ###
