"""add views field to Media

Revision ID: 6f530a3b2d21
Revises: ad1e25e08129
Create Date: 2025-10-12 04:28:53.504467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f530a3b2d21'
down_revision: Union[str, Sequence[str], None] = 'ad1e25e08129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('views', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'views')
    # ### end Alembic commands ###
