"""add width, height and duration to Media

Revision ID: 8036dffde3ca
Revises: a5c65309fe2a
Create Date: 2025-10-15 02:00:30.668079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8036dffde3ca'
down_revision: Union[str, Sequence[str], None] = 'a5c65309fe2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'duration')
    op.drop_column('media', 'height')
    op.drop_column('media', 'width')
    # ### end Alembic commands ###
