"""subscription table creation and background pic field added in users table

Revision ID: d9a730b9868c
Revises: 8036dffde3ca
Create Date: 2025-10-16 05:28:19.468153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9a730b9868c'
down_revision: Union[str, Sequence[str], None] = '8036dffde3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'creator_id', name='unique_subscription')
    )
    op.create_index(op.f('ix_subscriptions_creator_id'), 'subscriptions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscriber_id'), 'subscriptions', ['subscriber_id'], unique=False)
    op.add_column('users', sa.Column('background_pic_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'background_pic_url')
    op.drop_index(op.f('ix_subscriptions_subscriber_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_creator_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
