"""Added thumbnail_public_id to  media tables

Revision ID: e6c3c01ae949
Revises: 13b71ec1083c
Create Date: 2025-11-05 08:24:23.605810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6c3c01ae949'
down_revision: Union[str, Sequence[str], None] = '13b71ec1083c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('thumbnail_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('media', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'public_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('media', 'thumbnail_public_id')
    # ### end Alembic commands ###
